[workspace]
channels = ["conda-forge"]
name = "czi_container_from_position"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
start = "python main.py"

[dependencies]
numpy = ">=2.3.1,<3"
czifile = ">=2019.7.2.1,<2020"
